---
on:
  push: {}
  pull_request: {}

jobs:
  run_build:
    strategy:
      matrix:
        platform:
          - windows-latest
          - ubuntu-20.04
          - ubuntu-latest
          - mac-latest
        include:
        - platform: windows-latest
          python_version: '["<3.1", "<3.6", "3"]'
        - platform: ubuntu-20.04
          python_version: '["<3.6"]'
        - platform: ubuntu-latest
          python_version: '["3"]'
        - platform: mac-latest
          python_version: '["<3.6", "3"]'
    uses: ./.github/workflows/build.yaml
    with:
      platforms: '["${{ matrix.platform }}"]'
      python_version: ${{ matrix.python_version }}
